version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Running install phase..."
      - npm install

  pre_build:
    commands:
      - echo "Running post_build phase:"
      - echo "Running unit tests..."
      - npm run test
      - echo "Running e2e tests..."
      - npm run test:e2e
      - echo "Adding ecr credentials..."
      - REPOSITORY_URI=public.ecr.aws/d1z0u8i5/qwerty-ecr

  build:
    commands:
      - echo "Running docker build phase..."
      - - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo "Running post_build phase:"
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"qwerty-image","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
