version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Running install phase..."
      - npm install

  build:
    commands:
      - echo "Running build phase..."
      - npm run build

  post_build:
    commands:
      - echo "Running post_build phase:"
      - echo "Running unit tests..."
      - npm run test
      - echo "Running e2e tests..."
      - npm run test:e2e

artifacts:
  files:
    - '**/*'
